name: PR workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: '17'

jobs:
  lint-detekt:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-lint-detekt-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-lint-detekt-
            ${{ runner.os }}

      - name: Run detektAll task
        run: ./gradlew detektAll

  build-android:
    runs-on: ubuntu-latest
    needs: [ lint-detekt ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-android-
            ${{ runner.os }}

      - name: Build Android app
        run: ./gradlew :app:android:assemble

  build-ios:
    runs-on: macos-latest
    needs: [ lint-detekt ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-ios-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-ios-
            ${{ runner.os }}

      - name: Build KMP iOS Framework
        run: ./gradlew :app:shared:generateDummyFramework

      - name: Install CocoaPods
        run: |
          cd app/ios
          pod install

      - name: Build iOS App
        run: |
          cd app/ios
          xcodebuild \
            -workspace ios.xcworkspace \
            -scheme "Fifteen Puzzle" \
            -sdk iphonesimulator \
            -configuration Release \
            clean build

  unit-tests:
    runs-on: macos-latest
    needs: [ build-android, build-ios ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-unit-tests-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-unit-tests-
            ${{ runner.os }}

      - name: Run Kotlin unit tests
        run: ./gradlew test iosX64Test
